### ISSUE TITLE
Can I collaborate?

### ISSUE THREAD

**Issue by arqex** [luckyr13/arwiki-contracts#1]
Hi @luckyr13 

I'm just a newbie in the arweave community, but I'm very excited about the potential of it and how it allow to do new things!!

I was looking for examples of how a wiki would work and I found your project. I think it's looking great and it's very well organizedm and the best part is that you are actively working on it. I was thinking to read through the code and try to understand it.

While I'm learning about it I can write some comments to the methods and some readme docs. Do you think I can create a PR with all those and you can help me to understand them? At the end we'll have a very well documented code :) 

Cheers

**Comment by luckyr13** [comment]
Hello @arqex ! Welcome to ArWiki!

Yes, totally you can and I'm very happy to have you onboard. Please let me know if you need something, here's our Discord channel: https://discord.gg/mn8j66r4x3

You can find the first contract versions here: https://github.com/luckyr13/arwiki-contracts/tree/main/javascript

We are migrating the code to Typescript: https://github.com/luckyr13/arwiki-contracts/tree/main/typescript

Our ArWiki PST contract is based on the contract from CommunityXYZ, you can find their code here: https://github.com/cedriking/communityxzy-contract

I'm still working in our new version, so please be aware of changes.

Thank you and welcome 😄
